### PR TITLE
MentalsitFeedBack

### PR DESCRIPTION
**Pull request by MentalistTR**
Hello, vaishnaviVish,

I reviewed your code and found several improvements and security vulnerabilities; it also wasn't compiling.

1-) There were errors in module imports and the package name, and the version was incorrectly written; these have been corrected

2-) You cannot input 'balance' directly into the function as the 'Balance' struct is only capable of storing ability. Instead, you should input a 'u64'.

3-) You cannot return something as 'balance'. It needs to be returned as 'u64'. Additionally, the donation goal must be set as 'u64', not as 'Balance'.

4-) There are naming errors in the struct parameters; you need to pay attention to case sensitivity. You can see the updates in my commits.

5-) Function names should be meaningful. Here are some examples: 

CRUD functions names
These are the available CRUD functions:

add: Adds a value.
new: Creates an object.
drop: Drops a struct.
empty: Creates a struct.
remove: Removes a value.
exists_: Checks if a key exists.
contains: Checks if a collection contains a value.
destroy_empty: Destroys an object or data structure that has values with the drop ability.
to_object_name: Transforms an Object X to Object Y.
from_object_name: Transforms an Object Y to Object X.
property_name: Returns an immutable reference or a copy.
property_name_mut: Returns a mutable reference.

6-) Order arguments in functions: first objects, then primitive args, context last.

7-) An assert has been added to the Donate function to handle the possibility of sending 0 coins

8-) The endDonation function was very nonsensical. You close it with a bool, but the funds inside remain. We needed to transfer these funds.

9-) getDonorRecords function now can return the 3 variable. (there was some rust code :) )

10-) getTotalDonated function can return the total amount of donated as u64

11-) In the test section, you can see that all functions are working.

### CODE REVIEW

**Comment by vaishnaviVish** [comment]
Hello sir ,
I want to ask a question,after your correction ,now the code was deployed
and working or not in your machine

**Comment by MentalistTR** [comment]
Ekran Görüntüsü (1056)

yes it can compile and as you can see tests are passed. why did u asked that question ?

**Comment by vaishnaviVish** [comment]
Sir, because i got error when i test functions before,thats why i am asking
to you ,ki code is working or not

**Review by vaishnaviVish — COMMENTED** [review]
thankyou for fixing bugs

**Pull request merged**
